defaults:
    # General settings
    - generic_longitudinal
    - _self_

num_inter_by_epoch: 7
max_steps: 15000
lambda_reg: 0.01
lambda_sim: 0
lambda_seg: 1
learning_rate_svf: 0.001
save_dir: 'longitudinal/linear'
time_mode: "linear"
